import { ContactType, DealType, DealWidgetType, LeadType, OpportunitiesType } from '@/app/(admin)/(apps)/crm/types'
import { TbArrowDown, TbArrowUp, TbClock, TbCurrencyDollar } from 'react-icons/tb'

import user1 from '@/assets/images/users/user-1.jpg'
import user2 from '@/assets/images/users/user-2.jpg'
import user3 from '@/assets/images/users/user-3.jpg'
import user4 from '@/assets/images/users/user-4.jpg'
import user5 from '@/assets/images/users/user-5.jpg'
import user6 from '@/assets/images/users/user-6.jpg'
import user7 from '@/assets/images/users/user-7.jpg'
import user8 from '@/assets/images/users/user-8.jpg'
import user9 from '@/assets/images/users/user-9.jpg'
import user10 from '@/assets/images/users/user-10.jpg'

import googleLogo from '@/assets/images/logos/google.svg'
import microsoftLogo from '@/assets/images/logos/microsoft.svg'
import amazonLogo from '@/assets/images/logos/amazon.svg'
import appleLogo from '@/assets/images/logos/apple.svg'
import dropboxLogo from '@/assets/images/logos/dropbox.svg'
import slackLogo from '@/assets/images/logos/slack.svg'
import spotifyLogo from '@/assets/images/logos/spotify.svg'
import starbucksLogo from '@/assets/images/logos/starbucks.svg'
import airbnbLogo from '@/assets/images/logos/airbnb.svg'
import openaiLogo from '@/assets/images/logos/openai.svg'
import shellLogo from '@/assets/images/logos/shell.svg'
import figmaLogo from '@/assets/images/logos/figma.svg'
import asanaLogo from '@/assets/images/logos/asana.svg'

export const contacts: ContactType[] = [
  {
    id: 1,
    name: 'Emily Ross',
    email: 'emily.ross@greentech.com',
    phone: '+44 7911 112233',
    avatar: user1,
    label: { text: 'Prospect', variant: 'success' },
    description: 'Marketing Director at GreenTech',
    categories: [
      { name: 'Eco', variant: 'info' },
      { name: 'Newsletter', variant: 'light' },
      { name: 'Follow-up', variant: 'secondary' },
    ],
    stats: [
      { title: 'Posts', count: 98 },
      { title: 'Followers', count: 12.5, suffix: 'k' },
      { title: 'Followings', count: 860 },
    ],
  },
  {
    id: 2,
    name: 'Ava Mitchell',
    email: 'ava.mitchell@novaxlabs.com',
    phone: '+1 347 445 8890',
    avatar: user2,
    label: { text: 'Cold Lead', variant: 'info' },
    description: 'Product Strategist at NovaX Labs',
    categories: [
      { name: 'Technology', variant: 'primary' },
      { name: 'Outbound', variant: 'light' },
      { name: 'Low Engagement', variant: 'danger' },
    ],
    stats: [
      { title: 'Total Value', count: 4.2, suffix: 'k', prefix: '$' },
      { title: 'Open Deal', count: 1 },
      { title: 'Meetings', count: 0 },
    ],
  },
  {
    id: 3,
    name: 'Noah Johnson',
    email: 'noah.j@urbanmart.com',
    phone: '+1 212 776 2233',
    avatar: user3,
    label: { text: 'Hot Lead', variant: 'warning' },
    description: 'Sales Manager at UrbanMart',
    categories: [
      { name: 'Retail', variant: 'success' },
      { name: 'In-Person', variant: 'secondary' },
      { name: 'Urgent', variant: 'danger' },
    ],
    stats: [
      { title: 'Revenue', count: 12, suffix: 'k', prefix: '$' },
      { title: 'Open Deals', count: 3 },
      { title: 'Meetings', count: 5 },
    ],
  },
  {
    id: 4,
    name: 'Olivia Carter',
    email: 'olivia.carter@medisync.com',
    phone: '+44 20 7946 1000',
    avatar: user4,
    label: { text: 'Customer', variant: 'primary' },
    description: 'Operations Head at MediSync',
    categories: [
      { name: 'Healthcare', variant: 'danger' },
      { name: 'Newsletter', variant: 'secondary' },
      { name: 'Retention', variant: 'info' },
    ],
    stats: [
      { title: 'Tickets', count: 38 },
      { title: 'Resolved', count: 35 },
      { title: 'Pending', count: 3 },
    ],
  },
  {
    id: 5,
    name: 'Liam Brown',
    email: 'liam.brown@finverse.com',
    phone: '+1 415 901 8899',
    avatar: user5,
    label: { text: 'VIP', variant: 'danger' },
    description: 'Chief Finance Officer at Finverse',
    categories: [
      { name: 'Finance', variant: 'success' },
      { name: 'Investment', variant: 'primary' },
      { name: 'High Value', variant: 'danger' },
    ],
    stats: [
      { title: 'Transactions', count: 150 },
      { title: 'Value', count: 2.5, suffix: 'M', prefix: '$' },
      { title: 'Pending', count: 12 },
    ],
  },
  {
    id: 6,
    name: 'Sophia White',
    email: 'sophia.white@aerolite.com',
    phone: '+61 2 8890 4455',
    label: { text: 'Prospect', variant: 'success' },
    description: 'Project Manager at AeroLite',
    categories: [
      { name: 'Aerospace', variant: 'secondary' },
      { name: 'Follow-up', variant: 'info' },
    ],
    stats: [
      { title: 'Projects', count: 6 },
      { title: 'On Hold', count: 2 },
      { title: 'Active', count: 4 },
    ],
  },
  {
    id: 7,
    name: 'Ethan Walker',
    email: 'ethan.walker@nextgenai.com',
    phone: '+1 202 555 0181',
    avatar: user6,
    label: { text: 'Customer', variant: 'primary' },
    description: 'AI Engineer at NextGen AI',
    categories: [
      { name: 'Technology', variant: 'primary' },
      { name: 'Newsletter', variant: 'light' },
      { name: 'Loyal', variant: 'success' },
    ],
    stats: [
      { title: 'Models', count: 12 },
      { title: 'Deployed', count: 8 },
      { title: 'In Progress', count: 4 },
    ],
  },
  {
    id: 8,
    name: 'Mia Green',
    email: 'mia.green@biozen.com',
    phone: '+1 646 445 7788',
    avatar: user7,
    label: { text: 'Cold Lead', variant: 'info' },
    description: 'Research Scientist at BioZen',
    categories: [
      { name: 'Biotech', variant: 'success' },
      { name: 'Outbound', variant: 'secondary' },
    ],
    stats: [
      { title: 'Experiments', count: 45 },
      { title: 'Successful', count: 39 },
      { title: 'Failed', count: 6 },
    ],
  },
  {
    id: 9,
    name: 'James Wilson',
    email: 'james.wilson@buildmate.com',
    phone: '+44 161 555 2299',
    avatar: user8,
    label: { text: 'Prospect', variant: 'success' },
    description: 'Site Engineer at BuildMate',
    categories: [
      { name: 'Construction', variant: 'danger' },
      { name: 'Field', variant: 'secondary' },
    ],
    stats: [
      { title: 'Sites', count: 22 },
      { title: 'Completed', count: 17 },
      { title: 'Pending', count: 5 },
    ],
  },
  {
    id: 10,
    name: 'Isabella Martinez',
    email: 'isabella.m@creativespark.com',
    phone: '+1 213 555 9876',
    avatar: user9,
    label: { text: 'Hot Lead', variant: 'warning' },
    description: 'Creative Director at CreativeSpark',
    categories: [
      { name: 'Design', variant: 'info' },
      { name: 'Media', variant: 'secondary' },
    ],
    stats: [
      { title: 'Campaigns', count: 15 },
      { title: 'Successful', count: 12 },
      { title: 'Ongoing', count: 3 },
    ],
  },
  {
    id: 11,
    name: 'Benjamin Clark',
    email: 'ben.clark@healthplus.com',
    phone: '+1 917 445 3344',
    avatar: user10,
    label: { text: 'Customer', variant: 'primary' },
    description: 'CTO at HealthPlus',
    categories: [
      { name: 'Healthcare', variant: 'danger' },
      { name: 'Retention', variant: 'info' },
      { name: 'VIP', variant: 'success' },
    ],
    stats: [
      { title: 'Tickets', count: 87 },
      { title: 'Resolved', count: 82 },
      { title: 'Pending', count: 5 },
    ],
  },
  {
    id: 12,
    name: 'Charlotte King',
    email: 'charlotte.king@edusmart.com',
    phone: '+1 646 556 2211',
    label: { text: 'VIP', variant: 'danger' },
    description: 'Founder of EduSmart',
    categories: [
      { name: 'Education', variant: 'primary' },
      { name: 'High Value', variant: 'danger' },
    ],
    stats: [
      { title: 'Students', count: 20, suffix: 'k' },
      { title: 'Courses', count: 48 },
      { title: 'Mentors', count: 15 },
    ],
  },
]

export const opportunities: OpportunitiesType[] = [
  {
    id: '#OP007501',
    productName: 'Website Redesign Deal',
    productBy: 'Google Inc.',
    productLogo: googleLogo,
    customerName: 'John Carter',
    customerEmail: 'john@acme.com',
    customerAvatar: user1,
    stage: 'Proposal Sent',
    amount: '$12,500',
    closeDate: '15 Aug, 2025',
    source: 'Referral',
    owner: 'Sarah Johnson',
    status: 'open',
    priority: 'high',
  },
  {
    id: '#OP007502',
    productName: 'Enterprise SaaS Suite',
    productBy: 'Microsoft Corp.',
    productLogo: microsoftLogo,
    customerName: 'Priya Mehta',
    customerEmail: 'priya@globex.com',
    customerAvatar: user2,
    stage: 'Qualification',
    amount: '$50,000',
    closeDate: '10 Sep, 2025',
    source: 'LinkedIn',
    owner: 'Michael ih-p',
    status: 'in-progress',
    priority: 'medium',
  },
  {
    id: '#OP009123',
    productName: 'Cloud Analytics Pro',
    productBy: 'Google LLC',
    productLogo: googleLogo,
    customerName: 'Aarav Patel',
    customerEmail: 'aarav@nextgen.io',
    customerAvatar: user5,
    stage: 'Negotiation',
    amount: '$75,000',
    closeDate: '18 Oct, 2025',
    source: 'Website',
    owner: 'Sophia Lee',
    status: 'closed',
    priority: 'low',
  },
  {
    id: '#OP009201',
    productName: 'Retail Insights Pro',
    productBy: 'Amazon Inc.',
    productLogo: amazonLogo,
    customerName: 'Meena Roy',
    customerEmail: 'meena@retailhub.io',
    customerAvatar: user3,
    stage: 'Won',
    amount: '$92,000',
    closeDate: '02 Nov, 2025',
    source: 'Email',
    owner: 'Daniel Kim',
    status: 'closed',
    priority: 'high',
  },
  {
    id: '#OP009202',
    productName: 'AI Compute Suite',
    productBy: 'Apple Inc.',
    productLogo: appleLogo,
    customerName: 'Kabir Shah',
    customerEmail: 'kabir@aicore.ai',
    customerAvatar: user7,
    stage: 'Qualification',
    amount: '$64,500',
    closeDate: '15 Oct, 2025',
    source: 'Referral',
    owner: 'Emily Davis',
    status: 'open',
    priority: 'high',
  },
  {
    id: '#OP009203',
    productName: 'Ad Manager Pro',
    productBy: 'Dropbox',
    productLogo: dropboxLogo,
    customerName: 'Sana Iqbal',
    customerEmail: 'sana@adstack.com',
    customerAvatar: user4,
    stage: 'Won',
    amount: '$120,000',
    closeDate: '09 Dec, 2025',
    source: 'LinkedIn',
    owner: 'John Carter',
    status: 'closed',
    priority: 'low',
  },
  {
    id: '#OP009204',
    productName: 'TeamCollab Enterprise',
    productBy: 'Slack Technologies',
    productLogo: slackLogo,
    customerName: 'Jatin Desai',
    customerEmail: 'jatin@collabzone.net',
    customerAvatar: user6,
    stage: 'Proposal Sent',
    amount: '$48,000',
    closeDate: '30 Sep, 2025',
    source: 'Webinar',
    owner: 'Ashley Mio-p',
    status: 'in-progress',
    priority: 'low',
  },
  {
    id: '#OP009205',
    productName: 'Virtual Events Suite',
    productBy: 'Spotify Inc.',
    productLogo: spotifyLogo,
    customerName: 'Lina George',
    customerEmail: 'lina@meetpro.io',
    customerAvatar: user8,
    stage: 'Lost',
    amount: '$33,000',
    closeDate: '22 Oct, 2025',
    source: 'Cold Call',
    owner: 'Mark Evans',
    status: 'closed',
    priority: 'medium',
  },
  {
    id: '#OP009312',
    productName: 'Streamlytics Dashboard',
    productBy: 'Starbucks Inc.',
    productLogo: starbucksLogo,
    customerName: 'Ravi Khanna',
    customerEmail: 'ravi@streamlytics.co',
    customerAvatar: user10,
    stage: 'Qualification',
    amount: '$58,900',
    closeDate: '05 Nov, 2025',
    source: 'Trade Show',
    owner: 'Jessica Moore',
    status: 'in-progress',
    priority: 'high',
  },
  {
    id: '#OP009313',
    productName: 'Hospitality CRM Suite',
    productBy: 'Airbnb Inc.',
    productLogo: airbnbLogo,
    customerName: 'Isabella Wang',
    customerEmail: 'isabella@aircrm.com',
    customerAvatar: user9,
    stage: 'Proposal Sent',
    amount: '$41,200',
    closeDate: '12 Nov, 2025',
    source: 'Inbound',
    owner: 'Thomas Blake',
    status: 'open',
    priority: 'medium',
  },
]

export const dealWidgets: DealWidgetType[] = [
  {
    count: '1,230',
    change: '9.85%',
    icon: TbArrowUp,
    title: 'Total deals created',
    progress: 9.85,
    variant: 'primary',
  },
  {
    count: '860',
    change: '5.20%',
    icon: TbArrowUp,
    title: 'Deals won',
    progress: 5.2,
    variant: 'success',
  },
  {
    count: '270',
    change: '2.45%',
    icon: TbArrowDown,
    title: 'Deals lost',
    progress: 2.45,
    variant: 'danger',
  },
  {
    count: '$220,000',
    change: 'Top value',
    icon: TbCurrencyDollar,
    title: 'Highest deal closed',
    progress: 100,
    variant: 'warning',
  },
  {
    count: '5.2 days',
    change: '+1.1%',
    icon: TbClock,
    title: 'Avg. close time',
    progress: 1.1,
    variant: 'secondary',
  },
]

export const deals: DealType[] = [
  {
    id: 1,
    name: 'Enterprise Software',
    company: 'Google Inc',
    logo: googleLogo,
    amount: 102000,
    stage: 'Proposal Sent',
    probability: 65,
    date: '15 Aug, 2025',
  },
  {
    id: 2,
    name: 'Marketing Automation',
    company: 'Airbnb',
    logo: airbnbLogo,
    amount: 85000,
    stage: 'Qualified',
    probability: 55,
    date: '10 Aug, 2025',
  },
  {
    id: 3,
    name: 'Cloud Storage Deal',
    company: 'Dropbox',
    logo: dropboxLogo,
    amount: 47000,
    stage: 'Negotiation',
    probability: 80,
    date: '18 Aug, 2025',
  },
  {
    id: 4,
    name: 'AI Chatbot Integration',
    company: 'OpenAI',
    logo: openaiLogo,
    amount: 59500,
    stage: 'Proposal Sent',
    probability: 65,
    date: '22 Aug, 2025',
  },
  {
    id: 5,
    name: 'eCommerce Platform',
    company: 'Apple',
    logo: appleLogo,
    amount: 71200,
    stage: 'Qualification',
    probability: 45,
    date: '25 Aug, 2025',
  },
  {
    id: 6,
    name: 'Sales CRM Deal',
    company: 'Shell',
    logo: shellLogo,
    amount: 95000,
    stage: 'Won',
    probability: 100,
    date: '30 Aug, 2025',
  },
  {
    id: 7,
    name: 'Video Conferencing License',
    company: 'Figma Inc',
    logo: figmaLogo,
    amount: 38000,
    stage: 'Lost',
    probability: 0,
    date: '12 Sep, 2025',
  },
  {
    id: 8,
    name: 'Customer Support Suite',
    company: 'Starbucks',
    logo: starbucksLogo,
    amount: 52000,
    stage: 'Proposal Sent',
    probability: 70,
    date: '03 Sep, 2025',
  },
  {
    id: 9,
    name: 'Project Management SaaS',
    company: 'Slack',
    logo: slackLogo,
    amount: 44000,
    stage: 'Negotiation',
    probability: 60,
    date: '06 Sep, 2025',
  },
  {
    id: 10,
    name: 'Data Visualization Tool',
    company: 'Asana',
    logo: asanaLogo,
    amount: 67300,
    stage: 'Qualified',
    probability: 50,
    date: '10 Sep, 2025',
  },
  {
    id: 11,
    name: 'Team Chat Platform',
    company: 'Slack',
    logo: slackLogo,
    amount: 62000,
    stage: 'Won',
    probability: 100,
    date: '15 Sep, 2025',
  },
]

export const leadsData: LeadType[] = [
  {
    id: '#LD007842',
    customer: 'R. Thompson',
    company: 'Amazon Web Services',
    logo: amazonLogo,
    email: 'contact@aws.com',
    phone: '+1 206-555-0199',
    amount: 150000,
    tag: { label: 'Cloud', color: 'info' },
    assigned: { avatar: user10, name: 'Emily Carter' },
    status: 'In Progress',
    statusVariant: 'success',
    created: '12 Jul, 2025',
  },
  {
    id: '#LD007865',
    customer: 'S. Kapoor',
    company: 'Microsoft',
    logo: microsoftLogo,
    email: 's.kapoor@microt.com',
    phone: '+44 20 7946 0991',
    amount: 98500,
    tag: { label: 'AI', color: 'warning' },
    assigned: { avatar: user2, name: 'Liam Brown' },
    status: 'Proposal Sent',
    statusVariant: 'primary',
    created: '21 Jul, 2025',
  },
  {
    id: '#LD007866',
    customer: 'A. Patel',
    company: 'Google',
    logo: googleLogo,
    email: 'amit.patel@google.com',
    phone: '+1 650-253-0000',
    amount: 120000,
    tag: { label: 'Cloud', color: 'success' },
    assigned: { avatar: user3, name: 'Emily Wang' },
    status: 'Follow Up',
    statusVariant: 'info',
    created: '22 Jul, 2025',
  },
  {
    id: '#LD007867',
    customer: 'J. Fernandes',
    company: 'Airbnb Inc',
    logo: airbnbLogo,
    email: 'j.fernandes@adobe.com',
    phone: '+1 408-536-6000',
    amount: 65000,
    tag: { label: 'Design', color: 'danger' },
    assigned: { avatar: user4, name: 'Sara Kim' },
    status: 'Pending',
    statusVariant: 'warning',
    created: '23 Jul, 2025',
  },
  {
    id: '#LD007868',
    customer: 'M. Zhang',
    company: 'Apple Platforms',
    logo: appleLogo,
    email: 'ming.zhang@apple.com',
    phone: '+1 650-308-7300',
    amount: 142000,
    tag: { label: 'VR', color: 'secondary' },
    assigned: { avatar: user5, name: 'David Li' },
    status: 'In Progress',
    statusVariant: 'success',
    created: '23 Jul, 2025',
  },
  {
    id: '#LD007869',
    customer: 'N. Sharma',
    company: 'Asana',
    logo: asanaLogo,
    email: 'n.sharma@netflix.com',
    phone: '+1 408-540-3700',
    amount: 75500,
    tag: { label: 'Streaming', color: 'info' },
    assigned: { avatar: user6, name: 'Natalie Jones' },
    status: 'Rejected',
    statusVariant: 'danger',
    created: '24 Jul, 2025',
  },
  {
    id: '#LD007870',
    customer: 'K. Williams',
    company: 'Dropbox',
    logo: dropboxLogo,
    email: 'k.williams@tesila.com',
    phone: '+1 310-420-6600',
    amount: 110250,
    tag: { label: 'EV', color: 'dark' },
    assigned: { avatar: user7, name: 'Kevin Nguyen' },
    status: 'Negotiation',
    statusVariant: 'secondary',
    created: '24 Jul, 2025',
  },
  {
    id: '#LD007871',
    customer: 'L. Mehra',
    company: 'Airbnb',
    logo: airbnbLogo,
    email: 'l.mehra@airbnb.com',
    phone: '+1 415-555-0102',
    amount: 87000,
    tag: { label: 'Travel', color: 'danger' },
    assigned: { avatar: user8, name: 'Laura Mehra' },
    status: 'Proposal Sent',
    statusVariant: 'primary',
    created: '24 Jul, 2025',
  },
  {
    id: '#LD007872',
    customer: 'R. Iyer',
    company: 'Slack',
    logo: slackLogo,
    email: 'r.iyer@slackhq.com',
    phone: '+1 628-555-0111',
    amount: 332000,
    tag: { label: 'Collaboration', color: 'info' },
    assigned: { avatar: user9, name: 'Rohan Iyer' },
    status: 'In Progress',
    statusVariant: 'success',
    created: '24 Jul, 2025',
  },
  {
    id: '#LD007873',
    customer: 'E. Fernandez',
    company: 'Spotify',
    logo: spotifyLogo,
    email: 'emma.f@spotify.com',
    phone: '+46 31 123 456',
    amount: 917000,
    tag: { label: 'Music', color: 'success' },
    assigned: { avatar: user10, name: 'Emma Fernandez' },
    status: 'Pending',
    statusVariant: 'warning',
    created: '25 Jul, 2025',
  },
]
